version: '3'
services:
  app:
    build: .
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - .:/go/src
      - ~/.gitignore:/root/.gitignore
      - ~/.gitignore_global:/root/.gitignore_global
